# Generated by Django 4.0 on 2021-12-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
